public enum Breed_enum {
	AFFENPINSCHER, AKITA, AZAWAKH, BARBET, BEAGLE, BERNEDOODLE, BLOODHOUND, BRIARD, BULLDOG, CHIHUAHUA, CHOW_CHOW,  DALMATIAN, DACHSHUND, FOX_TERRIER, GOLDENDOODLE, HARRIER, KOMONDOR
}
