package console.realization;

public class main {

	public static void main(String[] args) {
		String user_film_dicription="A love story doomed by the depths of the Atlantic Ocean. Rose Calvert, now 101 reminiscences her experience of the Titanic, to American oceanic explorers, and her emotional connection with another passenger, Jack. Jack was an American starving artist who won a trip home on the Ship of Dreams to a lucky hand in poker. His luck unfortunately ran out on April 15, 1912 after colliding with an iceberg in the northern Mid-Atlantic. Four days before the unsinkable ship began to fill with ice cold sea water, Rose and Jack's love story began. Rose was suppose to marry her mother's pick of a fine gentlemen Cal Hockley, who was only attracted to Rose by her beauty and family fortune. Rose however felt she was in a crowded room screaming for help with no one to hear. Jack did hear her, with someone to finally listen, Rose couldn't deny her feelings for Jack anymore. Their love came to a new level, when Rose asked Jack to draw her like one of his \"french girls\" wearing only the rarest diamond, the Heart of the Ocean. A fun filled, romantic love affair between Jack and Rose couldn't be denied and Cal's pockets began to feel empty and he became jealous of Jack searching for a way to compromise Rose's love for Jack. The Titanic then collides with a large iceberg and begins to sink. As the ship lowers itself into the depths of the ocean, Jack and Rose must fight death of the freezing water and await a rescue ship. 84 years later Rose hears of the Titanic and the discovery of her drawing and meets with the explorers, her memories are where our story begins. The Titanic is a powerful story of survival, love and heroism. A love story that will never let go of the hearts of the people around the world.";
		String next_film_dicription="After winning a trip on the RMS Titanic during a dockside card game, American Jack Dawson spots the society girl Rose DeWitt Bukater who is on her way to Philadelphia to marry her rich snob fiancé Caledon Hockley. Rose feels helplessly trapped by her situation and makes her way to the aft deck and thinks of suicide until she is rescued by Jack. Cal is therefore obliged to invite Jack to dine at their first-class table where he suffers through the slights of his snobbish hosts. In return, he spirits Rose off to third-class for an evening of dancing, giving her the time of her life. Deciding to forsake her intended future all together, Rose asks Jack, who has made his living making sketches on the streets of Paris, to draw her in the nude wearing the invaluable blue diamond Cal has given her. Cal finds out and has Jack locked away. Soon afterwards, the ship hits an iceberg and Rose must find Jack while both must run from Cal even as the ship sinks deeper into the freezing water";		
		String test_string="Deep on the bottom of the sea, some 3800 meters below the surface of the freezing Atlantic Ocean, lies the wreckage of a ship. It is the unmistakable figure of the Titanic, once man's greatest mechanical achievement, now stripped of its former glory. Almost a century later, Brock Lovett, a modern treasure hunter intrigued by Titanic's hidden riches, and his well-equipped technical crew are digging for answers for the past three years; nevertheless, without any success. But, when Rose Calvert, one of Titanic's few survivors, learns about Lovett's crusade, she will begin to unfold her incredible, heartfelt and utterly tragic story that intertwines King Louis XVI's deep-blue \"Heart of the Ocean\" diamond, with her unlikely romance with the young bohemian vagabond, Jack Dawson. Can the past's mistakes teach a lesson in humility to both paupers and royalty?";
		Film user_film = new Film();
		Film next_film = new Film();
		String[] actors = { "Brad Pit", "Jhony Dap", "Morgan Freeman", "Orlando Blum" };
		String[] actors1 = { "Brad Pit", "Morgan Freeman", "Orlando Blum" };
	user_film.setDescription(user_film_dicription);
	next_film.setDescription(next_film_dicription);
	System.out.println(Film.calcRDF(user_film, next_film));

	
	}

}
